services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Aistea\LpBuilder\:
    resource: '../Classes/*'

  Aistea\LpBuilder\EventListener\InterviewInlineDuplicateControl:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Backend\Form\Event\ModifyInlineElementControlsEvent
